### ISSUE TITLE
This channel is already in use, continuing anyway

### ISSUE THREAD

**Issue by jjok** [margyle/decaf#14]
I get this message when calling `/relayControl`.

```
/var/mugsy/decaf/models.py:56: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(int(pinNumber), GPIO.OUT)
```

I think it's just a case of adding `GPIO.cleanup()` at the end of the function, so it's cleaned up for the next run.

**Comment by jjok** [comment]
Hmm... That doesn't seem to fix it. Not sure what to do?
Has anyone else seen this issue? Is it just because I'm running in Docker? It happens when I call the endpoint, then stop and start the container, the hit the endpoint again.

**Comment by margyle** [comment]
I haven't installed the Docker version, will do so tonight and check it out. I would have also expected the `GPIO.cleanup()` to do the trick.

**Comment by jjok** [comment]
And you haven't seen that warning when running straight on, presumably, Raspbian?

**Comment by margyle** [comment]
I do not see the warning in the json response. I do see it after calling the endpoint and then calling the pin from the terminal. I added the cleanup call to each section of the loop and it went away on subsequent calls:
`		if (repeatValue > 1):
			for _ in itertools.repeat(None, repeatValue):
				GPIO.output(int(pinNumber), GPIO.LOW)
				time.sleep(timeOn)
				GPIO.output(int(pinNumber), GPIO.HIGH)
				time.sleep(repeatDelay)
				GPIO.cleanup()
		else:
				GPIO.output(int(pinNumber), GPIO.LOW)
				time.sleep(timeOn)
				GPIO.output(int(pinNumber), GPIO.HIGH)
				GPIO.cleanup()`
Where did you add the `GPIO.cleanup()`?

**Comment by margyle** [comment]
I do not see the warning in the json response. I do see it after calling the endpoint and then calling the pin from the terminal. I added the cleanup call to each section of the loop and it went away on subsequent calls:

		`if (repeatValue > 1):
			for _ in itertools.repeat(None, repeatValue):
				GPIO.output(int(pinNumber), GPIO.LOW)
				time.sleep(timeOn)
				GPIO.output(int(pinNumber), GPIO.HIGH)
				time.sleep(repeatDelay)
				GPIO.cleanup()
		else:
				GPIO.output(int(pinNumber), GPIO.LOW)
				time.sleep(timeOn)
				GPIO.output(int(pinNumber), GPIO.HIGH)
				GPIO.cleanup()`

Where did you add the `GPIO.cleanup()`?

**Comment by jjok** [comment]
Hmm... I added it at the end. Right before the function returns.

```
if (repeatValue > 1):
		for _ in itertools.repeat(None, repeatValue):
			GPIO.output(int(pinNumber), GPIO.LOW)
			time.sleep(timeOn)
			GPIO.output(int(pinNumber), GPIO.HIGH)
			time.sleep(repeatDelay)
	else:
			GPIO.output(int(pinNumber), GPIO.LOW)
			time.sleep(timeOn)
			GPIO.output(int(pinNumber), GPIO.HIGH)
GPIO.cleanup()
```

**Comment by jjok** [comment]
I wonder it was whitespace-related? I was using `vi` and having trouble wrangling the tabs.

**Comment by margyle** [comment]
Maybe, but Python is pretty good about breaking and erroring out on any tab issues.  I'll install Docker and see what happens.

**Comment by margyle** [comment]
Having some issues with the Docker set up, doesn't appear to be using the mysql config. I know you mentioned something about that earlier. Will resolve but will be later tonight or tomo.

**Comment by jjok** [comment]
Did you run the commands in the same order as the README? The whole codebase (`./`) gets copied into the image at build time, so you have to have edited the config file before then.

Oh. Hang on. That's my problem, isn't it? :man_facepalming: That's why I wasn't seeing the change having any effect.

**Comment by margyle** [comment]
Ahhhhhh! That makes sense! Do I have to do anything special to rebuild? Like remove it first? Or does Docker know to just overwrite?

**Comment by jjok** [comment]
Nope. Just run the `build` command again. It should have cached all the steps that haven't changed since the last build, so it should just add the files again and do the last few bits, rather than installing everything as it did the first time. It should take seconds, rather than tens of minutes.

**Comment by jjok** [comment]
Surprisingly, my original fix works when I actually test it properly. I'll open a PR in a sec.

**Comment by margyle** [comment]
Sweet, thanks!
