### ISSUE TITLE
MySQL vs SQLite

### ISSUE THREAD

**Issue by etimoz** [margyle/decaf#24]
Is there a reason why you chose MySQL? I think it would be easier to just use SQLite and remove the dependency of running a separate service (mysql server). Performance wise I think there shouldn't be a big difference for this application.

**Comment by margyle** [comment]
I'm not tied to MySQL, mostly just went with what I knew best so I could hit the ground running. I probably won't have band with to make those conversions for at least a month or two but am happy to merge any changes the community makes.

**Comment by etimoz** [comment]
Nice, I'm working on it. I can provide the PR the next few days. 
I can also have a look into the testing issue  https://github.com/margyle/decaf/issues/20 if you don't mind.

**Comment by margyle** [comment]
Great! Really appreciate it. Totally cool with you jumping in anywhere you feel like you can make an impact. Also cool with folks opening up new issues for other design implementation discussions like this one. Cheers!

**Comment by jjok** [comment]
I think this is the perfect kind of application for SQLite. I had a look into it before, but I don't know Python that well, so I thought it would probably take me ages.
It will make the Docker image a lot simpler too.

**Comment by jjok** [comment]
There were some discussions about this on the message board a year or so ago, which you may be able to find...

**Comment by etimoz** [comment]
Nice, need to check out the other suggestions/discussion. I created a PR https://github.com/margyle/decaf/pull/25 for this issue, feel free to review.
Sry that there are that many changes in one PR, I will try to creating multiple PR in the future.
