### ISSUE TITLE
Foreign keys sql schema

### ISSUE THREAD

**Issue by etimoz** [margyle/decaf#26]
Adding foreign keys improves the maintainability of data and reduces cluttering of the database due to duplicates.

In a separate MR I added foreign keys to the sql schema along with some bootstrap data as a follow up on my last PR.

**Comment by etimoz** [comment]
Feel free to review https://github.com/margyle/decaf/pull/27

**Comment by margyle** [comment]
Thanks, will look at these tonight or tomo. Thanks again!
